name: Claudia

on:
  push:
    branches: [ main ]
    paths:
      - 'crop-tool/**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        WORKING_DIR: "./crop-tool"
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
         node-version: '14'
      - run: npm install
      
      - name: Install Claudia
        run: sudo npm install claudia -g
        
      - name: npm init
        run: sudo npm init -y
        
      - name: Claudia deploy nodejs application to aws lambda
        run: claudia create --region eu-west-2 --handler lambda.handler --set-env S3_BUCKET=crop-tool-images

      - name: Add S3 permissions to Claudia lambda execution role
        run: claudia add-s3-event-source --bucket crop-tool-images
